### ISSUE TITLE
Align information boxes vertically going bottom-up

### ISSUE THREAD

**Issue by szczura** [RickLeinecker/SeeShells#244]
Right now, the information boxes appear at the top of the scrollbar instead of the bottom. This can be an issue when you open a node with a lot of events and then click on a node with one or two events. The smaller node appears at first to have nothing pop up, but then you realize you have to scroll up to see anything.

# Normal view:
![image](https://user-images.githubusercontent.com/38367751/77240472-80f84780-6bbc-11ea-919f-066853b2a2ca.png)

# Example of what goes wrong:
Open up a node with a lot of events:
![image](https://user-images.githubusercontent.com/38367751/77240515-f8c67200-6bbc-11ea-9e43-b7766308e961.png)

You have to scroll up to see the 3 events for this node now:
![image](https://user-images.githubusercontent.com/38367751/77240506-d03e7800-6bbc-11ea-8524-aabb66e0cfc7.png)

# Possible solution:
- Keep track of what the largest number of events in a node are in the timelines.
- When clicking on a node, insert hidden/blank information boxes before inserting the actual information boxes. This would make them appear at the bottom .
-- Ex: The largest node holds 13 events. If a node with 2 events is clicked on, 11 hidden/blank information boxes are inserted before the actual information boxes about the 2 events are inserted. This aligns all the information boxes starting from the bottom instead of the top and prevents the user from having to scroll to see them.

**Comment by klaki892** [comment]
With the possible solution as stated,would the following test case still appear alright: 
1. I open a node with 8 events
2. I open a node with 3 events, the issue occurs
    a. We make the invisible boxes to make them appear all the way at the bottom
3. I open a node with 15 events

What happens to the node with 3 and 8 events?

**Comment by szczura** [comment]
> 
> 
> With the possible solution as stated,would the following test case still appear alright:
> 
>     1. I open a node with 8 events
> 
>     2. I open a node with 3 events, the issue occurs
>        a. We make the invisible boxes to make them appear all the way at the bottom
> 
>     3. I open a node with 15 events
> 
> 
> What happens to the node with 3 and 8 events?

So that is why I have the first bullet as keep track of what the largest number of events are in all the timelines. In this case, we would have padded both the 8 and 3 event nodes. This might give us some long vertical scrollbars unnecessarily, but it seems like it doesn't force a scroll all the way to the top when clicking on nodes; the long scrollbar shouldn't be TOO big of an issue until we come up with a better solution.

**Comment by bridCquinn** [comment]
At the moment, the way the blocks are created is all at once along with the nodes. The only reason you can't see them is because they are collapsed. So the largest stackedNode will have to be known and then that amount of boxes will need to be added.

**Comment by AlekStoyanov** [comment]
Upon working on implementing the solution mentioned above, I came to the unfortunate realization that it is not viable.
The issue is that there are too many invisible blocks that need to be added to the UI, which makes the UI thread work very long (impractically long). On top of that, the program as whole starts to hog insane amounts of ram which is unacceptable.
![image](https://user-images.githubusercontent.com/42561260/77807516-71667c00-705e-11ea-8e36-0e86d5a44c4e.png)

On top of the issue above, when two nodes are very close to each other there is still an issue of vertical misalignment as can be seen in the screenshot below.
![image](https://user-images.githubusercontent.com/42561260/77807586-ac68af80-705e-11ea-821f-c6e824afcb3e.png)
The green blocks are the "invisible" ones but for the sake of the example I have made them visible.

Here is a best case scenario, of what this solution would have looked like.
![image](https://user-images.githubusercontent.com/42561260/77807650-e043d500-705e-11ea-8905-cdb6df472f8f.png)
Again the "invisible" boxes have been made visible for the sake of the example.
